#!/usr/bin/env bash
#Display information about subdomains

func()
{
  if [ -z "$2" ]
  then
    subdominio=("www" "lb-01" "web-01" "web-02")
  else
    subdominio=( "$2" )
  fi 
  for subdomain in "${subdominio[@]}"
  do 
    echo -n "The subdomain $subdomain"
    dig "$subdomain.$1" | grep -A1 'ANSWER SECTION:' | tail -n -1\
    |awk '{ print " is a " $4 " record and points to " $5}' 
	done
}
func "$1" "$2"
exit 0
