#!/usr/bin/env bash
#Your Bash script must accept 2 arguments

func()
{
    if [ -z "$2" ]
    then
        sub_dominio=("www" "lb-01" "web-01" "web-02")
    else
	sub_dominio=("$2")
    fi
    for i in "${sub_dominio[@]}"
    do
        echo -n "The subdomain $i"
        dig "$i.$1" | grep -A1 'ANSWER SECTION:' | tail -n -1 |awk '{
	print " is a " $4 " record and points to " $5}'
    done
}
func "$1" "$2"
