#!/usr/bin/env bash
#Install nginx web server
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx Full'
sudo ufw allow 'Nginx HTTP'
sudo ufw allow 'Nginx HTTPS'
sudo chmod -R 777 /var/www/html/
sudo sed -i '/listen \[::]:80 default_server;/a rewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx start

