#!/usr/bin/env bash
#Install nginx web server
sudo apt-get update
sudo apt-get -y install nginx
sudo chmod -R 777 /var/www/html/
sudo echo "Hello World" | sudo tee /var/www/html/index.html
sudo sed -i '/server_name _;/a rewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/page.html
sudo sed -i '/server_name _;/a error_page 404 /page.html' /etc/nginx/sites-available/default
sudo service nginx start

