#!/usr/bin/env bash
#Install nginx web server
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx Full'
sudo ufw allow 'Nginx HTTP'
sudo ufw allow 'Nginx HTTPS'
sudo chmod -R 777 /var/www/html/
sudo echo "Hello World!" > /var/www/html/index.html
var=$(cat /proc/sys/kernel/hostname)
sudo sed -i '/http {/a add_header X-Served-By '"${var}"';' /etc/nginx/nginx.conf
sudo service nginx restart
