#!/usr/bin/env bash
# script that pings an IP address passed as an argument
args=("$@")
if [ "${args[0]}" ]
then
	ping -c 5 "${args[0]}"
else
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
