#!/usr/bin/env bash
# 100
echo "$$" > /var/run/myscript.pid
trap "echo I hate the kill command; rm /var/run/myscript.pid; exit" SIGTERM
trap "rm /var/run/myscript.pid; exit" SIGQUIT
trap "echo Y U no love me?!; exit" SIGINT
while :
do
	echo "To infinity and beyond"
	sleep 2
done
