#!/usr/bin/env bash
#Write a Bash script that configures the container 
sudo pkill apache2
sudo chmod 777 /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sudo -u nginx 'service nginx start'